seed: 42
name: #
pretrained_model:
  checkpoint_path: #
  architecture: SD1
  clip_skip: 2
fabric:
  precision: bf16-true
trainer:
  batch_size: 1
  grad_accum_steps: 1
  use_xformers: false
  noise_offset: 0.05
  snr_gamma: 5
  max_train:
    method: step
    value: 1000
optimizer:
  name: AnyPrecisionAdamW
lr_scheduler:
  name: cosine_with_restarts
  init_args:
    num_cycles: 3
    num_warmup_steps: 50
datapipe:
  path: #
  preprocess:
    cache_vae_outputs: false
    cache_te_outputs: false
  dataset:
    random_crop: true
    random_flip: true
    shuffle_tags: false
    caption_dropout: 0.0
  dataloader:
    drop_last: true
    pin_memory: true
    num_workers: 1
    persistent_workers: true
logging:
  logger: null
  save:
    every: step
    value: 100
  sample:
    every: step
    value: 100
    pipeline:
      prompt: "1girl, smile"
      negative_prompt: "bad quality, worse quality"
      width: 512
      height: 512
      num_inference_steps: 20
# Kohya default
peft:
  unet:
    type: LoRA
    lr: 0.0005
    parameters:
      r: 16
      lora_alpha: 8
      target_modules:
        - proj_in
        - proj_out
        - to_q
        - to_k
        - to_v
        - to_out.0
        - ff.net.0.proj
        - ff.net.2
      bias: "none"
  te:
    type: LoRA
      lr: 0.00005
      parameters:
        r: 16
        lora_alpha: 8
        target_modules:
          - k_proj
          - v_proj
          - q_proj
          - out_proj
          - fc1
          - fc2
        bias: "none"
