seed: 42
name: #
type: LoRA
pretrained_model:
  checkpoint_path: #
  architecture: SD1
  clip_skip: 2
fabric:
  precision: bf16-true
trainer:
  batch_size: 1
  grad_accum_steps: 1
  use_xformers: false
  noise_offset: 0.05
  snr_gamma: 5
  max_train:
    method: epoch
    value: 10
optimizer:
  name: AnyPrecisionAdamW
  init_args:
    lr: 0.0005
lr_scheduler:
  name: cosine_with_restarts
  init_args:
    num_cycles: 3
    num_warmup_steps: 50
datapipe:
  path: #
  preprocess:
    cache_vae_outputs: true
    cache_te_outputs: false
  dataset:
    random_crop: true
    random_flip: true
    shuffle_tags: false
    caption_dropout: 0.0
  dataloader:
    batch_size: ${trainer.batch_size}
    drop_last: true
    pin_memory: true
    num_workers: 1
    persistent_workers: true
logging:
  logger: null
  save:
    every: epoch
    value: 1
  sample:
    every: epoch
    value: 1
    pipeline:
      prompt: #
      negative_prompt: #
      width: 512
      height: 512
      num_inference_steps: 20
lora_unet:
  - r: 16
    target_modules: []
    lora_alpha: 16
    lora_dropout: 0.0
    bias: none
lora_te:
  - r: 16
    target_modules: []
    lora_alpha: 16
    lora_dropout: 0.0
    bias: none
